title: Research with R and Python
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! Here you will find tutorials on data analysis with R and Python. 
  I will also post past research to showcase a bit of my work. 
permalink: ':title/'
baseurl: "/Research" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Roberto Carcache Flores # add your name
author-img: rcf.jpg # add your photo
about-author: Data analysis and modelling is my passion. I'm currently studying an MSc. in Actuarial Science. Most of my work experience has been in the public sector as a consultant and research assistant.
social-github: rcarcacheflores 
social-linkedin: roberto-carcache-flores-05b5711a6/
social-email: rcarcacheflores@outlook.com

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
